require 'rubygems'
require 'rake'
require 'yaml'
require 'json'

TOPDIR = File.dirname(__FILE__)

desc "Test your cookbooks for syntax errors"
task :test do
  puts "** Testing your cookbooks for syntax errors"
  Dir[File.join(TOPDIR, "cookbooks", "**", "*.rb")].each do |recipe|
    sh %{ruby -c #{recipe}} do |ok, res|
      if !ok
        raise "Syntax error in #{recipe}"
      end
    end
  end
end

desc "By default, run rake test"
task :default => [:test]

namespace :chef do

  task :runsolo do
    chefroot            = TOPDIR
    main_config         = YAML.load(IO.read(TOPDIR + '/../config/cloud.yml'))
    profile             = ENV.key?('PROFILE') ? ENV['PROFILE'] : 'default'
    roles               = main_config[:profiles][profile.to_sym][:roles]
    roles_list          = roles.collect { |role| "role[#{role}]" }
    profile_config_file = "#{chefroot}/config/_#{profile}.json"
    profile_config      = {"run_list" => roles_list}.to_json
    File.open(profile_config_file, "w+") do |f|
      f.syswrite(profile_config)
    end

    system "cd #{chefroot} && chef-solo -j #{profile_config_file} -c #{chefroot}/config/solo.rb"
  end
  task :update do
    git_command = ENV['branch'] ? "git checkout #{ENV['branch']} && git pull" : "git pull"
    system "cd #{chefroot} && #{git_command}"
  end

end

